---
info:
  apiname: eapi-updatecustomer-rest
  status: ok
  version: v1_0_0
management:
  endpoints:
    web:
      base-path: /v1/pharmacy/patient/
      exposure:
        include: health,info
      path-mapping:
        info: ping
server:
  port: 8080

kafka:
  topic: dev-customer